pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - make test
      - make coverage
      - if test ${PYTHON_VERSION} = "3.6-jessie"; then make codecov; fi
    secrets: [ codecov_token ]

matrix:
  PYTHON_VERSION:
    - 2.7-wheezy
    - 3.5-jessie
    - 3.6-jessie
