pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - make test
      - make coverage
    secrets: [ codecov_token ]

matrix:
  PYTHON_VERSION:
    - 2.7-wheezy
    - 3.5-jessie
    - 3.6-jessie
