name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: compute tag name
        id: vars
        run: |
          TMPREF=${GITHUB_REF#refs/*/}
          if [[ "$TMPREF" == */merge ]]; then echo ::set-output name=tag::`echo pr${TMPREF} |awk -F '/' '{print $1;}'`; else echo ::set-output name=tag::${TMPREF}; fi
    - name: update setup.py
      run: |
        sed setup.py -e 's/version="dev"/version="${{ steps.vars.outputs.tag }}"/' -i
        cat setup.py | grep version
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        if: startsWith(github.ref, 'refs/tags/z')
        python setup.py sdist bdist_wheel
        twine upload dist/*
