name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: update setup.py
      run: |
        env | grep GITHUB
        TAG=${GITHUB_REF#refs/*/}
        echo $TAG
        sed setup.py -e "s/version=\"dev\"/version=\"$TAG\"/" -i
        cat setup.py | grep version
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        if: startsWith(github.ref, 'refs/tags/v')
        python setup.py sdist bdist_wheel
        twine upload dist/*
